export const ActionTypes = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_CATEGORIES: 'SET_CATEGORIES',
  SELECTED_PRODUCT: 'SELECTED_PRODUCT',
  SELECTED_CATEGORY: 'SELECTED_CATEGORY',
  REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
  REMOVE_SELECTED_CATEGORY: 'REMOVE_SELECTED_CATEGORY',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
};
